#
#   RPC Base Protocol
#
#   DESCRIPTION: 
#   AUTHOR: NickeyWoo <thenickey@gmail.com>
#   DATE: 2014/07/18
#

proto_library(
    name = 'RPCProto',
    srcs = [
        'RPCProto.proto',
        'RPCService.proto'
    ]
)


